### ISSUE TITLE
updated version T3Mac

### ISSUE THREAD

**Issue by Defragster** [onlykey/libraries#1]
I posted an updated version of this - that also pulls the processor unique 128 bit ID number.
https://forum.pjrc.com/threads/91-teensy-3-MAC-address?p=103646&viewfull=1#post103646

Only PJRC writes the serial/MAC bits as far as I know - not the bootloader - based on the one "non-TEENSY", 'teensy' I got.

**Comment by onlykey** [comment]
Thanks, for the MAC being uninitialized what issues does this cause? I would think that from a USB perspective everything would still work the same. Thanks for the updated library I will add this. I think for our purposes we may just use the 128 bit ID number instead of the MAC for one of the values we use to initialize the RNG.

**Comment by Defragster** [comment]
Unless the MAC is set - you can't count on it for anything but 1's.  It doesn't affect the USB - just seeing it as unique - like TYQT does.  Do you use TYQT?  It is an awesome debug/dev tool - and works with HID too.
If I get a forum answer I'm going to propose that folks making Teensy's might want to use a uniform use of the CHIP_ID with a LOCAL MAC header to look like a Teensy and never conflict in case some random chance made then.  In your case Paul might give you a block of his legit MAC space - then your devices would look like any other Teensy and not stand out on a machine if somebody wanted to know if it had seen an ONLYKEY ( at least not as easily/obviously ).

**Comment by onlykey** [comment]
Yes, good point. I have not tried TYQT yet but is sounds like a good tool. So one question in regards to making the OnlyKey look to whatever computer it is plugged into indistinguishable from a regular teensy, Does the MAC get read by the USB drivers or how would the system read this value?

**Comment by Defragster** [comment]
The MAC is just derived from the serial number - used in the context of a MAC with the prefix bytes.  Any other time it is just a 24 bit serial number - when set by PJRC - or board builder.  The USB code in the Teensy Tree just pulls that number and presents it as the serial number in "void usb_init_serialnumber(void)":
https://github.com/PaulStoffregen/cores/blob/master/teensy3/usb_desc.c#L1218

You could possibly ignore the write once area and just modify that code to pull a 'serial' number from EEPROM or elsewhere perhaps if I see it right? When used as a HID device I assume this same code is used?

But if you worked with Paul and got a block of reserved serial #'s and learned how to write the write once area - your devices would blend in over time. Your devices – like most – would never present as a MAC – that is only when used for Ethernet.  If you did it another way the end user could have control over it if you exposed it.

Teensy is so cool - and TYQT makes it more usable.  Given it doesn't have a real debugger getting usable debug spew is critical. TYQT allows GUI RESET over software - no button to push - integrates into Arduino so you can have 5 devices online and push code to an individual one (though it will associate a given sketch to a given device - unless you disassociate it between uploads). I've worked with some HID sketches and it seems to be good, though not as one to one as USB_Serial at times it seems. [one of those times is now - I just put a post on the TYQT thread]

**Comment by onlykey** [comment]
I guess my line of thinking here is in regards to security. Does having the MAC set to all FFs introduce a risk to the user where they could be identified as an OnlyKey user vs. a regular Teensy user. But the more I think about this I am not sure this really matters because if an attacker has access to a user's system and is able install malicious software that would obtain the MAC of the OnlyKey then at this point there are other easier ways of proving that the user is an OnlyKey user vs. a regular Teensy user, like seeing that they have the OnlyKey chrome app installed or just monitoring their keystrokes with a keylogger.

**Comment by Defragster** [comment]
I'm not sure of the crumbs HID leaves, perhaps the same Ser# on the port - my machine did pop up 'installing TeensyDuino HID' in some fashion yesterday (unrelated to onlykey) - I was initially assuming USB.  However anything that blends in to the Teensy universe would be one less unique/rare crumb to some degree once plugged in (plausible deniability) - adding other apps would leave their own signature.
Indeed if the camel's nose is sniffing it may not matter.

**Comment by onlykey** [comment]
I was able to verify that the MAC is FF: FF: FF: FF: FF: FF on the prototypes. At this point changing this to something unique is not on our roadmap as there are no plans to have the OnlyKey network capable. For the plausible deniability feature we are not attempting to make the OnlyKey look like a Teensy to the attached host so having a unique or non unique MAC would not be required for this feature. As far as I can tell nothing related to USB reads this value either so unless there is software specifically set up to query this the host would not read this.
